// Fixed in code on purpose: nothing in the deploy form or the Worker settings
// can point this Worker at a different server or trust a different key.

/**
 * This code's release number. Bump it on every release: QRCartoon compares it
 * with the latest and shows "Update available" in Settings.
 */
export const WORKER_VERSION = 4;

/** Where the Worker fetches its signed redirect list. */
export const QRC_API = "https://www.qrcartoon.com";

/**
 * QRCartoon's Ed25519 public keys (raw, base64). Bundles must be signed by one
 * of them. Two slots allow rotating the signing key without breaking Workers:
 * add the new key here, wait for users to redeploy, then switch signing.
 *
 * Generated by `bun scripts/generate-selfhost-key.ts`.
 */
export const PUBLIC_KEYS = [
	"hcuA3knL3Drul46XJdm1PCI+sJb8k3S+6p4wKGygO3U=", // added 2026-10-09
	"ibuugBwVfI/7xlc0aBxhvU9r7XrsQWFMDyukIthntjg=", // added 2026-10-08
	// PUBLIC_KEY_PLACEHOLDER — run the script above to fill this in.
];
